<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="14.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Repository\Repository.Abstractions\Repository.Abstractions.csproj" />
    <ProjectReference Include="..\Services.Abstractions\Services.Abstractions.csproj" />
    <ProjectReference Include="..\Services.Contract\Services.Contract.csproj" />
  </ItemGroup>

</Project>
