name: taskboard_project
services:
  taskboard-db:
   container-name: Database
   image: postgres:latest
   restart: always
   enviroment: 
      - POSTGRES_DB=taskboardDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGPORT=5432
  volumes:
      - postgres_database:/var/lib/postgressql/data
  ports:
      - 5432:5432
 networks: 
      - "taskboard_net"

  dotnet-webapi: 
    container-name: userService-webapi
    depends_on:
      - taskboard-db
  build: 
    context: ..
    dockerfile: ./src/UserService.Api/Dockerfile
  network: 
    taskboard-net
  enviroment: 
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__TaskboardDb=Host=Database;Username=postgres;Password=postgres;Database=taskboardDb;
  ports:
      - "7080:8080"
      - "7081:8081"
networks:
  taskboard-net:
    driver: bridge  
volumes: 
   postgres_database:         