syntax = "proto3";

option csharp_namespace = "UserService.Business.Services.GRPC";

package users;

// The user service definition
service UserService {
  rpc GetUser (GetUserRequestGRPC) returns (UserResponseGRPC);
  rpc GetUsers (GetUsersRequestGRPC) returns (UsersResponseGRPC);
}

// The request message containing the user ID
message GetUserRequestGRPC {
  string user_id = 1;
}

// The request message containing multiple user IDs
message GetUsersRequestGRPC {
  
}

// The response message containing multiple users
 
message UsersResponseGRPC {
  repeated UserResponseGRPC users = 1;
  
}

// The response message containing the user's details
message UserResponseGRPC {
  string user_id = 1;
  string email = 2;
  string first_name = 3;
  string last_name = 4;
  string display_name = 5;
}