name: taskboard-project
services:
  taskboard-db:
    container_name: Database
    image: postgres:latest
    restart: on-failure
    environment: 
      - POSTGRES_DB=taskboardDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGPORT=5433
    ports:
      - "5433:5433"
    volumes:
      - postgres-database:/var/lib/postgresql/data
    networks: 
      - taskboard-net
  #PowerShell Генерироовать сертифиакат
#dotnet dev-certs https -ep "$env:USERPROFILE\.aspnet\https\aspnetapp.pfx"  -p taskboardSert1
#dotnet dev-certs https --trust
  dotnet-webapi: 
    container_name: userService-webapi
    depends_on:
      - taskboard-db
    build: 
      context: .
      dockerfile: /UserService.Api/Dockerfile
    networks: 
      - taskboard-net
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=taskboardSert1
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ConnectionStrings__TaskboardDb=Host=Database;Username=postgres;Password=postgres;Database=taskboardDb;Port=5433;
    ports:
      - "7080:8080"
      - "7081:8081"
    restart: always
    volumes:
      - ~/.aspnet/https:/https:ro
  rabbit:
    image: rabbitmq:4-management
    restart: always
    hostname: rabbitmqhost    
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

networks:
  taskboard-net:
    driver: bridge  

volumes: 
  postgres-database:
  rabbitmq_data: